get http://localhost:8080/tests/test1

###
get http://localhost:8080/tests/test2

###
post http://localhost:8080/tests/test3
content-type: application/json

{
    "id": "1"
}
###
get http://localhost:8080/tests/test